import { useLocation } from "react-router-dom";
import { SEOHead } from "./SEOHead";

const seoMap: Record<string, { title: string; description: string }> = {
  "/": { title: "GRGF — Global Record Governance Foundation | Digital Public Infrastructure Standards Authority", description: "Independent global framework for Digital Public Infrastructure governance, validation, and institutional recognition." },
  "/about": { title: "About GRGF", description: "Why record governance matters and what the Global Record Governance Foundation is designed to solve." },
  "/architecture": { title: "System Architecture", description: "Three interdependent layers: Immutable Archive, Governance Operating System, and Digital Platform." },
  "/recognition": { title: "DPI Recognition Framework", description: "Structured, tiered accreditation pathway for institutions seeking verified governance integrity certification." },
  "/transparency": { title: "Transparency & Governance", description: "Public accountability documentation, governance charter, and institutional transparency commitments." },
  "/membership": { title: "Membership & Advisory", description: "Institutional membership tiers, advisory services, and strategic partnership engagement pathways." },
  "/contact": { title: "Contact", description: "Reach the Global Record Governance Foundation for institutional inquiries and partnership discussions." },
  "/oecd-alignment": { title: "OECD Institutional Alignment", description: "How GRGF aligns with OECD Digital Public Infrastructure standards and multilateral governance frameworks." },
  "/ethics": { title: "Governance Ethics", description: "Anti-capture clauses, risk controls, and the institutional neutrality framework governing GRGF operations." },
  "/compliance": { title: "Standards Compliance", description: "Regulatory compliance documentation, audit methodologies, and governance integrity verification standards." },
  "/dpi-stack": { title: "DPI Stack Architecture", description: "Technical architecture of the six-layer Digital Public Infrastructure governance stack." },
  "/safeguards-trust": { title: "Safeguards & Trust", description: "Privacy-by-design, zero-trust security, and high-availability resilience architecture for governance integrity." },
  "/deployment-scenarios": { title: "Deployment Scenarios", description: "National and international deployment models for sovereign governance infrastructure implementation." },
  "/academy": { title: "GRGF Academy", description: "Professional certification programs and governance integrity training for institutional practitioners." },
  "/archive": { title: "Digital Archive", description: "Authoritative document archive with hash-verified integrity proofs for all governance framework materials." },
  "/research": { title: "Research & Publications", description: "Academic publications, technical papers, and governance research from the GRGF standards body." },
  "/partnerships": { title: "Global Partnerships", description: "Strategic partnership framework for multilateral collaboration and federation node participation." },
  "/controlled-access": { title: "Controlled Access", description: "Request governance assessment, submit recognition applications, or access restricted institutional materials." },
  "/privacy-policy": { title: "Privacy Policy", description: "GRGF privacy policy covering data protection, GDPR compliance, and institutional privacy commitments." },
  "/terms-of-service": { title: "Terms of Service", description: "Terms governing use of the GRGF digital platform and institutional governance services." },
  "/sitemap": { title: "Site Map", description: "Complete navigation index of all GRGF platform pages and institutional resources." },
  "/what-is-grgf": { title: "What Is GRGF?", description: "Introduction to the Global Record Governance Foundation and its role in Digital Public Infrastructure." },
  "/how-it-works": { title: "How It Works", description: "Step-by-step guide to how GRGF processes governance events and creates verifiable records." },
  "/the-problem": { title: "The Problem", description: "Understanding the $2.6 trillion annual cost of governance failures and institutional accountability gaps." },
  "/governance": { title: "Governance Model", description: "Institutional governance architecture including board structure, standards committees, and oversight mechanisms." },
  "/governance-framework": { title: "Governance Framework", description: "Detailed governance framework documentation for institutional record integrity standards." },
  "/security": { title: "Security Architecture", description: "Cryptographic security infrastructure, threat modeling, and zero-trust architecture for governance records." },
  "/verification": { title: "Record Verification", description: "Independent verification tools and cryptographic proof validation for governance record integrity." },
  "/impact-modeling": { title: "Impact Modeling", description: "Economic impact analysis and governance integrity ROI modeling for institutional deployment." },
  "/impact-roi": { title: "Impact & ROI", description: "Return on investment analysis for Digital Public Infrastructure governance deployment." },
  "/simulation": { title: "Governance Simulation", description: "Interactive simulation environment for governance event processing and policy enforcement testing." },
  "/pilot-programme": { title: "Pilot Programme", description: "National pilot implementation programme for sovereign governance infrastructure deployment." },
  "/pilot-evaluation": { title: "Pilot Evaluation", description: "Evaluation criteria and assessment methodology for governance pilot deployments." },
  "/canada-deployment": { title: "Canada Deployment", description: "Canadian national deployment strategy for GRGF governance infrastructure pilot programme." },
  "/international-cooperation": { title: "International Cooperation", description: "Cross-border federation protocol and regional strategic frameworks for multilateral governance." },
  "/countries": { title: "Country Profiles", description: "Regional deployment readiness assessments and institutional governance maturity profiles." },
  "/use-cases": { title: "Use Cases", description: "Real-world governance integrity use cases across procurement, social benefits, and regulatory compliance." },
  "/stakeholder-solutions": { title: "Stakeholder Solutions", description: "Tailored governance integrity solutions for governments, auditors, and international organizations." },
  "/risk-mitigation": { title: "Risk Mitigation", description: "Institutional risk management framework and governance failure prevention strategies." },
  "/future-proofing": { title: "Future Proofing", description: "Post-quantum readiness roadmap and long-term architectural resilience planning." },
  "/source-of-truth": { title: "Source of Truth", description: "Authoritative master record architecture and cryptographic chain-of-custody documentation." },
  "/records": { title: "Governance Records", description: "Record management framework for institutional governance events, decisions, and omissions." },
  "/dpi-comparison": { title: "DPI Comparison", description: "Comparative analysis of GRGF against traditional GovTech and other Digital Public Infrastructure layers." },
  "/processes": { title: "Operational Processes", description: "Standard operating procedures and institutional process documentation for governance operations." },
  "/systems": { title: "System Components", description: "Technical component catalogue for the governance infrastructure operating system." },
  "/executive-summary": { title: "Executive Summary", description: "High-level institutional overview of the Global Record Governance Foundation for decision-makers." },
  "/executive-dossier": { title: "Executive Dossier", description: "Comprehensive executive briefing package for institutional leadership and governance stakeholders." },
  "/institutional-briefing": { title: "Institutional Briefing", description: "Structured briefing materials for institutional review committees and governance boards." },
  "/institutional-readiness": { title: "Institutional Readiness", description: "Readiness assessment framework for organizations preparing for governance infrastructure adoption." },
  "/critical-questions": { title: "Critical Questions", description: "Frequently asked institutional questions about jurisdiction, privacy, data admissibility, and sovereignty." },
  "/validation-pathway": { title: "Validation Pathway", description: "Structured validation and certification pathway for institutional governance compliance." },
  "/strategic-governance": { title: "Strategic Governance", description: "Long-term strategic governance planning and institutional transformation roadmap." },
  "/national-deployment": { title: "National Deployment", description: "National-scale deployment framework for sovereign governance infrastructure implementation." },
  "/operational-model": { title: "Operational Model", description: "Day-to-day operational model for governance infrastructure management and maintenance." },
  "/data-entry": { title: "Data Entry", description: "Governance data ingestion and event capture interface for institutional record creation." },
  "/simulator": { title: "Governance Simulator", description: "Interactive governance event simulator for testing policy enforcement and record creation." },
  "/dashboard": { title: "Dashboard", description: "Governance integrity dashboard with real-time metrics and system status monitoring." },
  "/dashboards": { title: "Analytics Dashboards", description: "Comprehensive analytics and reporting dashboards for governance performance monitoring." },
  "/workflow-demo": { title: "Workflow Demo", description: "Interactive demonstration of governance workflow processing and institutional event handling." },
  "/outreach-messages": { title: "Outreach Messages", description: "Institutional outreach communications and partnership engagement templates." },
  "/technical-blueprints": { title: "Technical Blueprints", description: "Detailed technical architecture blueprints for governance infrastructure implementation." },
  "/system-architecture": { title: "System Architecture Detail", description: "In-depth system architecture documentation for the governance infrastructure platform." },
  "/security-trust": { title: "Security & Trust", description: "Security assurance framework and institutional trust architecture documentation." },
  "/governance-interface": { title: "Governance Interface", description: "Administrative governance interface for institutional record management operations." },
  "/origin": { title: "Origin Story", description: "The founding vision and institutional genesis of the Global Record Governance Foundation." },
  "/oecd-safeguards": { title: "OECD DPI Safeguards Scorecard", description: "Interactive self-assessment aligned with the OECD five-pillar Digital Public Infrastructure safeguards framework." },
  "/open-standards": { title: "Open Standards & Interoperability", description: "Machine-readable schema declarations, API standards, and data portability commitments for governance infrastructure." },
  "/risk-register": { title: "Public Risk Register", description: "Structured risk disclosure matrix identifying and documenting mitigation strategies for institutional risks." },
  "/sustainability": { title: "Digital Sustainability", description: "Environmental impact assessment, digital carbon footprint statement, and sustainability commitments." },
  "/human-rights-impact": { title: "Human Rights Impact Assessment", description: "Formal HRIA aligned with UN Guiding Principles on Business and Human Rights." },
  "/stakeholder-consultation": { title: "Stakeholder Consultation", description: "Structured public consultation mechanism for governance standards development and review." },
  "/world-bank-alignment": { title: "World Bank GovTech Alignment", description: "GovTech Maturity Index mapping and Digital Development Principles alignment for governance infrastructure." },
  "/un-alignment": { title: "UN SDG & Digital Public Goods", description: "Sustainable Development Goals impact assessment and Digital Public Goods Alliance standard compliance." },
  "/g20-dpi-framework": { title: "G20 DPI Framework Alignment", description: "G20 Digital Public Infrastructure principles alignment and Layer 3 governance integrity positioning." },
  "/itu-global-standards": { title: "ITU & Regional Standards", description: "ITU-T standard alignment and regional digital governance framework mapping worldwide." },
  "/international-compliance": { title: "International Compliance Hub", description: "Comprehensive multilateral alignment dashboard across OECD, World Bank, UN, G20, ITU, and regional frameworks." },
};

export function RouteSEO() {
  const { pathname } = useLocation();
  const seo = seoMap[pathname];
  if (!seo) return <SEOHead title="GRGF" description="Global Record Governance Foundation — Digital Public Infrastructure Standards Authority." />;
  return <SEOHead title={seo.title} description={seo.description} />;
}
